/**
 * File organizer - groups Terraform resources by target file
 * Based on spec section 7.14
 */

import { TerraformResource } from '../types/terraform.types';
import { FileMap } from '../types/config.types';

/**
 * Organize resources by filename and generate file content
 *
 * Groups resources by their fileName property and concatenates their HCL
 * with appropriate file headers.
 *
 * @param resources - Array of Terraform resources with generated HCL
 * @returns Map of filename to file content
 *
 * @example
 * const fileMap = organizeByFile(resources)
 * // => { 'checks_api.tf': '# Generated...\nresource ...', ... }
 */
export function organizeByFile(resources: TerraformResource[]): FileMap {
  const fileMap: FileMap = {};

  // Group resources by fileName
  const grouped: { [filename: string]: TerraformResource[] } = {};

  for (const resource of resources) {
    if (!grouped[resource.fileName]) {
      grouped[resource.fileName] = [];
    }
    grouped[resource.fileName].push(resource);
  }

  // Generate file content for each group
  for (const [filename, resourceList] of Object.entries(grouped)) {
    let content = '# Generated by tf-checks-from-json\n';
    content += '# Source: urlList.json\n\n';

    for (const resource of resourceList) {
      if (resource.hcl) {
        content += resource.hcl + '\n';
      }
    }

    fileMap[filename] = content;
  }

  return fileMap;
}
